package hbm;

// Generated 18/05/2015 10:23:33 PM by Hibernate Tools 3.4.0.CR1

import hbm.dto.Customer;
import hbm.dto.OrderId;
import hbm.dto.Product;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "test")
public class Order implements java.io.Serializable {

	private OrderId id;
	private Product product;
	private Customer customer;
	private int quantity;
	private double price;
	private double fullPrice;
	private Date orderDate;
	private int status;
	private String comment;

	public Order() {
	}

	public Order(OrderId id, Product product, Customer customer, int quantity,
			double price, double fullPrice, Date orderDate, int status) {
		this.id = id;
		this.product = product;
		this.customer = customer;
		this.quantity = quantity;
		this.price = price;
		this.fullPrice = fullPrice;
		this.orderDate = orderDate;
		this.status = status;
	}

	public Order(OrderId id, Product product, Customer customer, int quantity,
			double price, double fullPrice, Date orderDate, int status,
			String comment) {
		this.id = id;
		this.product = product;
		this.customer = customer;
		this.quantity = quantity;
		this.price = price;
		this.fullPrice = fullPrice;
		this.orderDate = orderDate;
		this.status = status;
		this.comment = comment;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "idCustomer", column = @Column(name = "id_customer", nullable = false)) })
	public OrderId getId() {
		return this.id;
	}

	public void setId(OrderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_customer", nullable = false, insertable = false, updatable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 3)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "full_price", nullable = false, precision = 3)
	public double getFullPrice() {
		return this.fullPrice;
	}

	public void setFullPrice(double fullPrice) {
		this.fullPrice = fullPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "comment", length = 50)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
