package hbm.dto;

// Generated 18/05/2015 10:23:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DebtDetailByCustomerId generated by hbm2java
 */
@Embeddable
public class DebtDetailByCustomerId implements java.io.Serializable {

	private int idProduct;
	private String productName;
	private double price;
	private double fullPrice;
	private int quantity;
	private Date orderDate;
	private String comment;
	private String customerName;
	private String email;
	private int idCustomer;

	public DebtDetailByCustomerId() {
	}

	public DebtDetailByCustomerId(int idProduct, String productName,
			double price, double fullPrice, int quantity, Date orderDate,
			String customerName, int idCustomer) {
		this.idProduct = idProduct;
		this.productName = productName;
		this.price = price;
		this.fullPrice = fullPrice;
		this.quantity = quantity;
		this.orderDate = orderDate;
		this.customerName = customerName;
		this.idCustomer = idCustomer;
	}

	public DebtDetailByCustomerId(int idProduct, String productName,
			double price, double fullPrice, int quantity, Date orderDate,
			String comment, String customerName, String email, int idCustomer) {
		this.idProduct = idProduct;
		this.productName = productName;
		this.price = price;
		this.fullPrice = fullPrice;
		this.quantity = quantity;
		this.orderDate = orderDate;
		this.comment = comment;
		this.customerName = customerName;
		this.email = email;
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "product_name", nullable = false, length = 50)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "price", nullable = false, precision = 3)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "full_price", nullable = false, precision = 3)
	public double getFullPrice() {
		return this.fullPrice;
	}

	public void setFullPrice(double fullPrice) {
		this.fullPrice = fullPrice;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "order_date", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "comment", length = 50)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "customer_name", nullable = false, length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DebtDetailByCustomerId))
			return false;
		DebtDetailByCustomerId castOther = (DebtDetailByCustomerId) other;

		return (this.getIdProduct() == castOther.getIdProduct())
				&& ((this.getProductName() == castOther.getProductName()) || (this
						.getProductName() != null
						&& castOther.getProductName() != null && this
						.getProductName().equals(castOther.getProductName())))
				&& (this.getPrice() == castOther.getPrice())
				&& (this.getFullPrice() == castOther.getFullPrice())
				&& (this.getQuantity() == castOther.getQuantity())
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this
						.getOrderDate() != null
						&& castOther.getOrderDate() != null && this
						.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getComment() == castOther.getComment()) || (this
						.getComment() != null && castOther.getComment() != null && this
						.getComment().equals(castOther.getComment())))
				&& ((this.getCustomerName() == castOther.getCustomerName()) || (this
						.getCustomerName() != null
						&& castOther.getCustomerName() != null && this
						.getCustomerName().equals(castOther.getCustomerName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& (this.getIdCustomer() == castOther.getIdCustomer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduct();
		result = 37
				* result
				+ (getProductName() == null ? 0 : this.getProductName()
						.hashCode());
		result = 37 * result + (int) this.getPrice();
		result = 37 * result + (int) this.getFullPrice();
		result = 37 * result + this.getQuantity();
		result = 37 * result
				+ (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37 * result
				+ (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37
				* result
				+ (getCustomerName() == null ? 0 : this.getCustomerName()
						.hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + this.getIdCustomer();
		return result;
	}

}
