package hbm.dto;

// Generated 18/05/2015 10:23:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DebtDetailByCustomer generated by hbm2java
 */
@Entity
@Table(name = "debt_detail_by_customer", catalog = "test")
public class DebtDetailByCustomer implements java.io.Serializable {

	private DebtDetailByCustomerId id;

	public DebtDetailByCustomer() {
	}

	public DebtDetailByCustomer(DebtDetailByCustomerId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "productName", column = @Column(name = "product_name", nullable = false, length = 50)),
			@AttributeOverride(name = "price", column = @Column(name = "price", nullable = false, precision = 3)),
			@AttributeOverride(name = "fullPrice", column = @Column(name = "full_price", nullable = false, precision = 3)),
			@AttributeOverride(name = "quantity", column = @Column(name = "quantity", nullable = false)),
			@AttributeOverride(name = "orderDate", column = @Column(name = "order_date", nullable = false, length = 19)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 50)),
			@AttributeOverride(name = "customerName", column = @Column(name = "customer_name", nullable = false, length = 100)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 50)),
			@AttributeOverride(name = "idCustomer", column = @Column(name = "id_customer", nullable = false)) })
	public DebtDetailByCustomerId getId() {
		return this.id;
	}

	public void setId(DebtDetailByCustomerId id) {
		this.id = id;
	}

}
