package hbm.dto;

// Generated 18/05/2015 10:23:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PaymentsByCustomer generated by hbm2java
 */
@Entity
@Table(name = "payments_by_customer", catalog = "test")
public class PaymentsByCustomer implements java.io.Serializable {

	private PaymentsByCustomerId id;

	public PaymentsByCustomer() {
	}

	public PaymentsByCustomer(PaymentsByCustomerId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProduct", column = @Column(name = "id_product", nullable = false)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, precision = 3)),
			@AttributeOverride(name = "paymentDate", column = @Column(name = "payment_date", nullable = false, length = 19)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 100)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 50)),
			@AttributeOverride(name = "idCustomer", column = @Column(name = "id_customer", nullable = false)) })
	public PaymentsByCustomerId getId() {
		return this.id;
	}

	public void setId(PaymentsByCustomerId id) {
		this.id = id;
	}

}
