package hbm.dto;

// Generated 18/05/2015 10:23:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentsByCustomerId generated by hbm2java
 */
@Embeddable
public class PaymentsByCustomerId implements java.io.Serializable {

	private int idProduct;
	private double amount;
	private Date paymentDate;
	private String name;
	private String email;
	private int idCustomer;

	public PaymentsByCustomerId() {
	}

	public PaymentsByCustomerId(int idProduct, double amount, Date paymentDate,
			String name, int idCustomer) {
		this.idProduct = idProduct;
		this.amount = amount;
		this.paymentDate = paymentDate;
		this.name = name;
		this.idCustomer = idCustomer;
	}

	public PaymentsByCustomerId(int idProduct, double amount, Date paymentDate,
			String name, String email, int idCustomer) {
		this.idProduct = idProduct;
		this.amount = amount;
		this.paymentDate = paymentDate;
		this.name = name;
		this.email = email;
		this.idCustomer = idCustomer;
	}

	@Column(name = "id_product", nullable = false)
	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "amount", nullable = false, precision = 3)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "payment_date", nullable = false, length = 19)
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "id_customer", nullable = false)
	public int getIdCustomer() {
		return this.idCustomer;
	}

	public void setIdCustomer(int idCustomer) {
		this.idCustomer = idCustomer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentsByCustomerId))
			return false;
		PaymentsByCustomerId castOther = (PaymentsByCustomerId) other;

		return (this.getIdProduct() == castOther.getIdProduct())
				&& (this.getAmount() == castOther.getAmount())
				&& ((this.getPaymentDate() == castOther.getPaymentDate()) || (this
						.getPaymentDate() != null
						&& castOther.getPaymentDate() != null && this
						.getPaymentDate().equals(castOther.getPaymentDate())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& (this.getIdCustomer() == castOther.getIdCustomer());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProduct();
		result = 37 * result + (int) this.getAmount();
		result = 37
				* result
				+ (getPaymentDate() == null ? 0 : this.getPaymentDate()
						.hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + this.getIdCustomer();
		return result;
	}

}
